# syntax=docker/dockerfile:1.7
# ============================================================
# Multi-app monorepo Dockerfile
# Usage: docker build --build-arg APP_NAME=my-app .
# ============================================================

# ---- Pin base images by digest for reproducibility --------
FROM node:20-alpine AS base
# Enable corepack so pnpm version comes from package.json#packageManager
RUN corepack enable && corepack prepare --activate
WORKDIR /app


# ============================================================
# Stage 1: Install ALL dependencies (cached aggressively)
# Only re-runs when lockfile or package manifests change.
# ============================================================
FROM base AS deps

# Copy manifests first — widest cache layer
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Copy every package.json in the monorepo (preserves workspace structure)
# .dockerignore must exclude node_modules, dist, .turbo, .git
COPY apps/*/package.json           ./apps-manifests/
COPY packages/*/package.json       ./packages-manifests/

# Reconstruct the directory structure expected by pnpm workspaces
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    # Restore manifests into their real paths before install
    find apps-manifests -name 'package.json' | while read f; do \
      dir="apps/$(basename $(dirname $f))"; \
      mkdir -p "$dir" && cp "$f" "$dir/"; \
    done && \
    find packages-manifests -name 'package.json' | while read f; do \
      dir="packages/$(basename $(dirname $f))"; \
      mkdir -p "$dir" && cp "$f" "$dir/"; \
    done && \
    rm -rf apps-manifests packages-manifests && \
    pnpm install --frozen-lockfile --prefer-offline


# ============================================================
# Stage 2: Build the selected app
# ============================================================
FROM deps AS builder

ARG APP_NAME
# Fail early if APP_NAME was not provided
RUN test -n "$APP_NAME" || (echo "APP_NAME build arg is required" && exit 1)

# Copy workspace-level configs (only what's needed for the build)
COPY tsconfig.json              ./
COPY turbo.json                 ./
# Use a glob-safe COPY: if either vite config is absent Docker won't error
# because we're copying from a source that may contain one or both.
COPY vite.config.*              ./

# Copy source — app + any local packages it depends on
COPY apps/$APP_NAME             ./apps/$APP_NAME
COPY packages                   ./packages

# Copy the .env.production generated by CI (injected by the pipeline)
# If absent the build continues — the app should handle missing vars gracefully
COPY apps/$APP_NAME/.env.production* ./apps/$APP_NAME/

# Build only the target app and its deps via Turbo
# Mount the Turbo cache so it persists across BuildKit builds
RUN --mount=type=cache,id=turbo,target=/root/.cache/turbo \
    TURBO_CACHE_DIR=/root/.cache/turbo \
    pnpm turbo build --filter=@dans-framework/$APP_NAME

# Verify dist was actually produced
RUN test -d "apps/$APP_NAME/dist" || \
    (echo "Build did not produce apps/$APP_NAME/dist — check turbo.json outputs" && exit 1)


# ============================================================
# Stage 3: Production nginx image (minimal, hardened)
# ============================================================
FROM nginx:1.27-alpine AS runtime

ARG APP_NAME
RUN test -n "$APP_NAME" || (echo "APP_NAME build arg is required" && exit 1)

# Write the full nginx config inline — no external file dependencies
RUN cat > /etc/nginx/conf.d/default.conf <<'EOF'
server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # ---- Compression ----------------------------------------
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/javascript application/javascript
               application/json application/xml image/svg+xml;

    # ---- Security headers -----------------------------------
    add_header X-Frame-Options           "SAMEORIGIN"             always;
    add_header X-Content-Type-Options    "nosniff"                always;
    add_header X-XSS-Protection          "1; mode=block"          always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy        "camera=(), microphone=(), geolocation=()" always;
    add_header Content-Security-Policy
        "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self';"
        always;

    # Remove server fingerprint
    server_tokens off;

    # ---- SPA routing ----------------------------------------
    location / {
        try_files $uri $uri/ /index.html;
    }

    # ---- Cache static assets --------------------------------
    location ~* \.(?:js|css|woff2?|ttf|eot|ico|png|jpg|jpeg|svg|gif|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # ---- Health endpoint ------------------------------------
    location /health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    # ---- Block hidden files ---------------------------------
    location ~ /\. {
        deny all;
    }
}
EOF

# Fix ownership so nginx user can write to required dirs
RUN chown -R nginx:nginx \
        /usr/share/nginx/html \
        /var/cache/nginx \
        /var/log/nginx \
        /etc/nginx/conf.d && \
    # nginx needs to write its pid file as non-root
    touch /var/run/nginx.pid && chown nginx:nginx /var/run/nginx.pid

# Copy built assets
COPY --from=builder --chown=nginx:nginx \
     /app/apps/$APP_NAME/dist /usr/share/nginx/html

USER nginx
EXPOSE 8080

HEALTHCHECK --interval=15s --timeout=3s --start-period=5s --retries=3 \
    CMD wget -qO- http://localhost:8080/health || exit 1

CMD ["nginx", "-g", "daemon off;"]