services:
  ohsmart:
    image: dansknaw/dans-frontend-framework-ohsmart:latest
    restart: unless-stopped
    container_name: ohsmart-demo
    networks:
      - traefik
    ports:
      - "8000:80"
  rda:
    image: dansknaw/dans-frontend-framework-rda:latest
    restart: unless-stopped
    container_name: rda-demo
    networks:
      - traefik
    ports:
      - "8002:80"
  swh:
    image: dansknaw/dans-frontend-framework-swh:latest
    restart: unless-stopped
    container_name: swh-demo
    networks:
      - traefik
    ports:
      - "8003:80"
  cat:
    image: dansknaw/dans-frontend-framework-cat:latest
    restart: unless-stopped
    container_name: cat-demo
    networks:
      - traefik
    ports:
      - "8005:80"
  4tu:
    image: dansknaw/dans-frontend-framework-4tu:latest
    restart: unless-stopped
    container_name: 4tu-demo
    networks:
      - traefik
    ports:
      - "8006:80"
  digitaltwins:
    image: dansknaw/dans-frontend-framework-digitaltwins:latest
    restart: unless-stopped
    container_name: digitaltwins-demo
    networks:
      - traefik
    ports:
      - "8007:80"
  supercatalog:
    image: dansknaw/dans-frontend-framework-supercatalog:latest
    restart: unless-stopped
    container_name: supercatalog-demo
    networks:
      - traefik
    ports:
      - "8008:80"
  fair-assessment:
    image: dansknaw/dans-frontend-framework-fair-assessment:latest
    restart: unless-stopped
    container_name: fair-assessment-demo
    networks:
      - traefik
    ports:
      - "8010:80"
  eden:
    image: dansknaw/dans-frontend-framework-eden:latest
    restart: unless-stopped
    container_name: eden-demo
    networks:
      - traefik
    ports:
      - "8011:80"

networks:
  traefik:
    external: true