version: "3.9"
services:
  ohsmart:
    image: dansknaw/ohsmart:latest
    restart: unless-stopped
    container_name: ohsmart-demo
    networks:
      - traefik
    ports:
      - "8000:80"
  rda:
    image: dansknaw/rda:latest
    restart: unless-stopped
    container_name: rda-demo
    networks:
      - traefik
    ports:
      - "8002:80"
  swh:
    image: dansknaw/swh:latest
    restart: unless-stopped
    container_name: swh-demo
    networks:
      - traefik
    ports:
      - "8003:80"
  cat:
    image: dansknaw/cat:latest
    restart: unless-stopped
    container_name: cat-demo
    networks:
      - traefik
    ports:
      - "8005:80"
  4tu:
    image: dansknaw/4tu:latest
    restart: unless-stopped
    container_name: 4tu-demo
    networks:
      - traefik
    ports:
      - "8006:80"
  digitaltwins:
    image: dansknaw/digitaltwins:latest
    restart: unless-stopped
    container_name: digitaltwins-demo
    networks:
      - traefik
    ports:
      - "8007:80"
  supercatalog:
    image: dansknaw/supercatalog:latest
    restart: unless-stopped
    container_name: supercatalog-demo
    networks:
      - traefik
    ports:
      - "8008:80"
  rda-sandbox:
    image: dansknaw/rda-sandbox:latest
    restart: unless-stopped
    container_name: rda-sandbox-demo
    networks:
      - traefik
    ports:
      - "8009:80"
  fair-assessment:
    image: dansknaw/fair-assessment:latest
    restart: unless-stopped
    container_name: fair-assessment-demo
    networks:
      - traefik
    ports:
      - "8010:80"
  eden:
    image: dansknaw/eden:latest
    restart: unless-stopped
    container_name: eden-demo
    networks:
      - traefik
    ports:
      - "8011:80"

networks:
  traefik:
    external: true