name: Docker Image CI

on:
  push:
    tags:
      - "beta-*"
      - "alpha-*"
      - "v1.*"
    paths:
      - 'apps/faircore4eosc/**'

jobs:

  test:

    runs-on: ohsmart
    strategy:
      matrix:
        node-version: ["18"]
    name: Run tests
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
        npm install --global yarn
        yarn global add turbo
        yarn global add pnpm
    - name: Run tests
      run: "echo 'setup complete' "

  push:

    name: Push to registry.
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: ["18"]
    env:
      IMAGE_TAG: ${{ github.ref_name }}
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_NAME: "dans-frontend-framework-fc4e"
      ORG: "dansknaw"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to dockerhub
      run: |
        docker build -f apps/ohsmart/Dockerfile . -t $ORG/$IMAGE_NAME:$IMAGE_TAG
        docker push $ORG/$IMAGE_NAME:$IMAGE_TAG
